version: "3.8"

services:
  backend:
    image: booksapi.azurecr.io/backend
    build:
      context: .
    command: /bin/sh /django/start-backend.sh
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
    domainname: "booksapi"
  
  db:
    image: postgres
    env_file:
      - .env
    networks:
      - djangonetwork
  
networks:
  djangonetwork:
    driver: bridge