# Generated by Django 4.0.4 on 2022-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='books.author'),
        ),
        migrations.DeleteModel(
            name='AuthorBookRelation',
        ),
    ]
